# ./.tmuxinator.yml
# launch this with `tmuxinator start theme=ONLY_THE_NAME_OF_THEME_FOLDER`

name: YOUR_TMUX_WINDOW_NAME
root: <%= ENV["PWD"] %>

on_project_first_start: sudo systemctl start docker

on_project_stop: docker-compose down

startup_window: docker

windows:
  - git: git fetch --all
  - docker: ["systemctl status docker", "q", "docker-compose up -d"]
  - theme: [cd wp-content/themes/<%= @settings["theme"] %>, lsta ]
