version: '3.8'

services:
  db:
    container_name: "wp-mysql"
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wp_wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - database:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: unless-stopped

  wordpress:
    container_name: "wp-site"
    depends_on:
      - db
    image: fsg/wordpress
    build:
      context: .
      dockerfile: Dockerfile.website
      args:
        user_id: ${UID:-1000}
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    # ports:
    #   - "8000:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_wordpress

  caddy:
    container_name: caddy
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - wordpress:/var/www/html  # share WordPress files

volumes:
  database:
  wordpress:
  caddy_data:
  caddy_config: